server:
  port: 8080
  shutdown: graceful
  
#spring:
#  jpa:
#    show-sql: true
#  datasource:
#    url: jdbc:oracle:thin:@oratest.popso.it:1521/oltptestsrv.popso.it
#    username: BICOMP
#    password: BICOMP_9471
#    driver-class-name: oracle.jdbc.OracleDriver

#=============================================================
# Bicomp parameters
#=============================================================
bicomp:
  datasource:
    url: jdbc:oracle:thin:@oratest.popso.it:1521/oltptestsrv.popso.it
    #username: BICOMP
    #password: BICOMP_9471
    username: ${BICOMP_USERNAME}
    password: ${BICOMP_PASSWORD}
    driver: oracle.jdbc.OracleDriver
  hibernate:
    dialect: org.hibernate.dialect.OracleDialect
    show-sql: false
    format-sql: false
    
#=============================================================
# T2C parameters
#=============================================================
t2c:
  datasource:
    url: jdbc:oracle:thin:@oratest.popso.it:1521/osptestsrv.popso.it
    #username: TLM_T2C
    #password: TLM_T2C_1246
    username: ${T2C_USERNAME}
    password: ${T2C_PASSWORD}
    driver: oracle.jdbc.OracleDriver
  hibernate:
    dialect: org.hibernate.dialect.OracleDialect
    show-sql: false
    format-sql: false

#=============================================================
# SLT parameters
#=============================================================
slt:
  datasource:
    url: jdbc:db2://db2svi.popso.it:50000/DB2S
    #username: SLTW01
    #password: SLTWEB
    username: ${SLT_USERNAME}
    password: ${SLT_PASSWORD}
    driver: com.ibm.db2.jcc.DB2Driver
  hibernate:
    dialect: org.hibernate.dialect.DB2Dialect
    show-sql: false
    format-sql: false


minio:
  url: http://localhost:9000
  access:
    name: minioadmin
    secret: minioadmin
  bucket:
    name: alessio