server:
  port: 8080
  shutdown: graceful

#=============================================================
# Bicomp parameters
#=============================================================
bicomp:
  datasource:
    url: ${BICOMP_DB_URL}
    username: ${BICOMP_USERNAME}
    password: ${BICOMP_PASSWORD}
    driver: oracle.jdbc.OracleDriver
  hibernate:
    show-sql: false
    format-sql: false
    
#=============================================================
# T2C parameters
#=============================================================
t2c:
  datasource:
    url: ${T2C_DB_URL}
    username: ${T2C_USERNAME}
    password: ${T2C_PASSWORD}
    driver: oracle.jdbc.OracleDriver
  hibernate:
    show-sql: false
    format-sql: false

#=============================================================
# SLT parameters
#=============================================================
slt:
  datasource:
    url: ${SLT_DB_URL}
    username: ${SLT_USERNAME}
    password: ${SLT_PASSWORD}
    driver: com.ibm.db2.jcc.DB2Driver
  hibernate:
    show-sql: false
    format-sql: false

#=============================================================
# MinIO parameters
#=============================================================
minio:
  url: http://localhost:9000
  access:
    name: minioadmin
    secret: minioadmin
  bucket:
    name: alessio